### ISSUE TITLE
Kerberize cluster

### ISSUE THREAD

**Issue by kumarcraja** [kumarcraja/cloudera#12]
starting

**Comment by kumarcraja** [comment]
kerberos server ready while enabling kerberos heap error showing

**Comment by kumarcraja** [comment]
heap size reduced for Namnode to available and running

**Comment by kumarcraja** [comment]
kerberos enabled for cm

**Comment by kumarcraja** [comment]
running terasort started

**Comment by kumarcraja** [comment]
started running pi

**Comment by kumarcraja** [comment]
submitted

**Comment by mfernest** [comment]
Missing the ACL file from `/var/kerberos/krb5kdc/`

INC
