### ISSUE TITLE
Installation Lab

### ISSUE THREAD

**Issue by kumarcraja** [kumarcraja/cloudera#2]
Cloudera Installation Lab

**Comment by kumarcraja** [comment]
Started

**Comment by kumarcraja** [comment]
status update
Unable to launch instances ...
![screenshot from 2016-12-05 12 29 35](https://cloud.githubusercontent.com/assets/23572552/20876428/f2c98894-bae7-11e6-9bd1-d269cf99f567.png)
![screenshot from 2016-12-05 12 32 26](https://cloud.githubusercontent.com/assets/23572552/20876431/f4c2f7ac-bae7-11e6-8010-3d046126efab.png)

**Comment by kumarcraja** [comment]
Requested AWS support via mail and by creating support case. Now I am able to create 3 instances only. Starting with three instances ...
![three_instances](https://cloud.githubusercontent.com/assets/23572552/20877149/9d62a2be-baec-11e6-94c3-ddcaea7a5139.png)

**Comment by kumarcraja** [comment]
Region settings is the issue for me for instances limit ...

Changed region settings as per the mail communications, Now five instances launched ...

![five_instances](https://cloud.githubusercontent.com/assets/23572552/20877359/2af40bf8-baee-11e6-8e3f-b79003c987ae.png)

**Comment by kumarcraja** [comment]
logged in using the following command after setting up pubic ip to node names in /etc/hosts file.

```
ssh -i ~/Downloads/craja1.pem  -l ec2-user node1
```

**Comment by kumarcraja** [comment]
vm.swapiness set to 1 in all nodes
```[root@ip-172-31-1-209 sbin]# cat /proc/sys/vm/swappiness 
1
[root@ip-172-31-1-209 sbin]# ./cluster_fork 'cat /proc/sys/vm/swappiness'
1
1
1
1
```

**Comment by kumarcraja** [comment]
Mount attributes of disks in all nodes
=============================
```
[root@ip-172-31-1-209 sbin]# mount | grep xvda
/dev/xvda2 on / type xfs (rw,relatime,seclabel,attr2,inode64,noquota)
[root@ip-172-31-1-209 sbin]# ./cluster_fork 'mount | grep xvda'aa
/dev/xvda2 on / type xfs (rw,relatime,seclabel,attr2,inode64,noquota)
/dev/xvda2 on / type xfs (rw,relatime,seclabel,attr2,inode64,noquota)
/dev/xvda2 on / type xfs (rw,relatime,seclabel,attr2,inode64,noquota)
/dev/xvda2 on / type xfs (rw,relatime,seclabel,attr2,inode64,noquota)
[root@ip-172-31-1-209 sbin]# 
```

**Comment by kumarcraja** [comment]
For the above two steps.

Password less ssh enabled for root user to all nodes.

Identified all hosts network ips and configured /etc/hosts as follows
====================================================

172.31.1.209 node1
172.31.1.208 node2
172.31.1.207 node3
172.31.1.210 node4
172.31.1.211 node5

Also created two custom script sync configuration fie to all nodes, and run commands in all nodes.

custer_fork

```
[root@ip-172-31-1-209 sbin]# cat cluster_fork 
#!/bin/bash

for node in node2 node3 node4 node5
do
ssh $node $*
done
```

cluster_scp

```
#!/bin/bash

for node in node2 node3 node4 node5
do
rsync -rvlogtP $1 $node:$2
done
```



We are using xfs file system, no reserve space for any root user

**Comment by kumarcraja** [comment]
We are using xfs file system, no reserve space for any non root user
=================================================

**Comment by kumarcraja** [comment]
transparent_hugepage disabled
=========================

```
[root@ip-172-31-1-209 sbin]# cat /sys/kernel/mm/transparent_hugepage/enabled 
always madvise [never]

[root@ip-172-31-1-209 sbin]# ./cluster_fork 'cat /sys/kernel/mm/transparent_hugepage/enabled'
[always] madvise never
[always] madvise never
[always] madvise never
[always] madvise never
```

**Comment by kumarcraja** [comment]
Network interface details
====================

eth0 172.31.1.209 node1
eth0 172.31.1.208 node2
eth0 172.31.1.207 node3
eth0 172.31.1.210 node4
eth0 172.31.1.211 node5

**Comment by kumarcraja** [comment]
Checking host name  look-ups
=======================

```
[root@ip-172-31-1-209 sbin]# cat /etc/hosts
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6


172.31.1.209 ip-172-31-1-209.us-west-2.compute.internal
172.31.1.208 ip-172-31-1-208.us-west-2.compute.internal
172.31.1.207 ip-172-31-1-207.us-west-2.compute.internal
172.31.1.210 ip-172-31-1-210.us-west-2.compute.internal
172.31.1.211 ip-172-31-1-211.us-west-2.compute.internal
[root@ip-172-31-1-209 sbin]# cat /etc/resolv.conf 
# Generated by NetworkManager
search us-west-2.compute.internal
nameserver 172.31.0.2
[root@ip-172-31-1-209 sbin]# getent hosts ip-172-31-1-209.us-west-2.compute.internal
172.31.1.209    ip-172-31-1-209.us-west-2.compute.internal
[root@ip-172-31-1-209 sbin]# getent hosts 172.31.1.209
172.31.1.209    ip-172-31-1-209.us-west-2.compute.internal
[root@ip-172-31-1-209 sbin]# nslookup ip-172-31-1-209.us-west-2.compute.internal
Server:		172.31.0.2
Address:	172.31.0.2#53

Non-authoritative answer:
Name:	ip-172-31-1-209.us-west-2.compute.internal
Address: 172.31.1.209

[root@ip-172-31-1-209 sbin]# nslookup 172.31.1.209
Server:		172.31.0.2
Address:	172.31.0.2#53

Non-authoritative answer:
209.1.31.172.in-addr.arpa	name = ip-172-31-1-209.us-west-2.compute.internal.

Authoritative answers can be found from:

[root@ip-172-31-1-209 sbin]# 
```

**Comment by kumarcraja** [comment]
Verifying nscd services
=================

[root@ip-172-31-1-209 sbin]# systemctl status nscd > /dev/null; echo $?
0
[root@ip-172-31-1-209 sbin]# ./cluster_fork 'systemctl status nscd > /dev/null; echo $?'
0
0
0
0
[root@ip-172-31-1-209 sbin]#

**Comment by kumarcraja** [comment]
Verifying ntpd service
=================

[root@ip-172-31-1-209 sbin]# systemctl status ntpd > /dev/null; echo $?
0
[root@ip-172-31-1-209 sbin]# ./cluster_fork 'systemctl status ntpd > /dev/null; echo $?'
0
0
0
0
[root@ip-172-31-1-209 sbin]#

**Comment by kumarcraja** [comment]
Mysql Server replication status
========================


mysql> 
mysql> show slave status \G
*************************** 1. row ***************************
               Slave_IO_State: Waiting for master to send event
                  Master_Host: ip-172-31-1-209.us-west-2.compute.internal
                  Master_User: root
                  Master_Port: 3306
                Connect_Retry: 60
              Master_Log_File: ip-172-31-1-209-bin.000001
          Read_Master_Log_Pos: 154
               Relay_Log_File: ip-172-31-1-208-relay-bin.000002
                Relay_Log_Pos: 330
        Relay_Master_Log_File: ip-172-31-1-209-bin.000001
             Slave_IO_Running: Yes
            Slave_SQL_Running: Yes
              Replicate_Do_DB: 
          Replicate_Ignore_DB: 
           Replicate_Do_Table: 
       Replicate_Ignore_Table: 
      Replicate_Wild_Do_Table: 
  Replicate_Wild_Ignore_Table: 
                   Last_Errno: 0
                   Last_Error: 
                 Skip_Counter: 0
          Exec_Master_Log_Pos: 154
              Relay_Log_Space: 547
              Until_Condition: None
               Until_Log_File: 
                Until_Log_Pos: 0
           Master_SSL_Allowed: No
           Master_SSL_CA_File: 
           Master_SSL_CA_Path: 
              Master_SSL_Cert: 
            Master_SSL_Cipher: 
               Master_SSL_Key: 
        Seconds_Behind_Master: 0
Master_SSL_Verify_Server_Cert: No
                Last_IO_Errno: 0
                Last_IO_Error: 
               Last_SQL_Errno: 0
               Last_SQL_Error: 
  Replicate_Ignore_Server_Ids: 
             Master_Server_Id: 1
                  Master_UUID: 0af9989a-bad2-11e6-a314-0a726d2d2bab
             Master_Info_File: /var/lib/mysql/master.info
                    SQL_Delay: 0
          SQL_Remaining_Delay: NULL
      Slave_SQL_Running_State: Slave has read all relay log; waiting for more updates
           Master_Retry_Count: 86400
                  Master_Bind: 
      Last_IO_Error_Timestamp: 
     Last_SQL_Error_Timestamp: 
               Master_SSL_Crl: 
           Master_SSL_Crlpath: 
           Retrieved_Gtid_Set: 
            Executed_Gtid_Set: 
                Auto_Position: 0
         Replicate_Rewrite_DB: 
                 Channel_Name: 
           Master_TLS_Version: 
1 row in set (0.00 sec)

mysql>

**Comment by mfernest** [comment]
It's not necessary to show the details of each exercise in the Issue. We can use this space just to track the high-level steps.

If it suits you to put all the details here, however, go ahead.

**Comment by kumarcraja** [comment]
![screenshot from 2016-12-05 20 50 24](https://cloud.githubusercontent.com/assets/23572552/20890383/b349ee58-bb2c-11e6-96dd-d64c0f9d0a21.png)

**Comment by kumarcraja** [comment]
![screenshot from 2016-12-05 21 07 00](https://cloud.githubusercontent.com/assets/23572552/20890959/dff90b62-bb2e-11e6-807c-a7a3c412bc1e.png)

**Comment by kumarcraja** [comment]
![screenshot from 2016-12-05 21 32 23](https://cloud.githubusercontent.com/assets/23572552/20891984/73ed2a80-bb32-11e6-9d36-a71ab9c1d1ef.png)

**Comment by kumarcraja** [comment]
![screenshot from 2016-12-05 21 34 50](https://cloud.githubusercontent.com/assets/23572552/20892081/bda810c2-bb32-11e6-88dd-e1aa75f8a9fd.png)

**Comment by kumarcraja** [comment]
![screenshot from 2016-12-05 22 10 01](https://cloud.githubusercontent.com/assets/23572552/20893443/ce2940f6-bb37-11e6-80a6-3a399bb5692d.png)

**Comment by kumarcraja** [comment]
submitted

**Comment by mfernest** [comment]
Please relocate your lab files to `labs/` directory. Remove the `incomplete` flag when this is done.

**Comment by kumarcraja** [comment]
Thank you,

relocated files labs/ directory, and removed incomplete flag

Please check the same ...

**Comment by mfernest** [comment]
👍
