### ISSUE TITLE
Storage labs

### ISSUE THREAD

**Issue by kumarcraja** [kumarcraja/cloudera#3]
Storage labs Started

**Comment by kumarcraja** [comment]
After snapshot created directory is deletable ...

```
[kumarcraja@ip-172-31-1-209 ~]$ hdfs dfs -rmdir /user/kumarcraja/precious
rmdir: The directory /user/kumarcraja/precious cannot be deleted since /user/kumarcraja/precious is snapshottable and already has snapshots
[kumarcraja@ip-172-31-1-209 ~]$ 
```

**Comment by kumarcraja** [comment]
![2_snapshot_list png](https://cloud.githubusercontent.com/assets/23572552/20913099/ebc74618-bb9a-11e6-8719-57061122e90b.png)

**Comment by kumarcraja** [comment]
![3_hdfs_ha](https://cloud.githubusercontent.com/assets/23572552/20913101/f36cb45c-bb9a-11e6-93ee-ea2458b1e6bd.png)

**Comment by kumarcraja** [comment]
![4_cm_users](https://cloud.githubusercontent.com/assets/23572552/20913104/fa554fcc-bb9a-11e6-8b30-c1a439b8616c.png)

**Comment by kumarcraja** [comment]
http://54.202.206.44:7180/cmf/login

**Comment by kumarcraja** [comment]
URL to Cloudera Manager instance

http://54.202.206.44:7180/cmf/login

**Comment by kumarcraja** [comment]
uploded files to labs directtory ...

![4_cm_users](https://cloud.githubusercontent.com/assets/23572552/20922844/9aae805e-bbcf-11e6-8589-ae941994cefb.png)

**Comment by mfernest** [comment]
👍
