### ISSUE TITLE
secutiry labs

### ISSUE THREAD

**Issue by kumarcraja** [kumarcraja/cloudera#5]
started

**Comment by kumarcraja** [comment]
![cm_creds](https://cloud.githubusercontent.com/assets/23572552/20965238/cbd5057e-bc9a-11e6-82a9-b0a0a7f7e30f.png)

Integrated kerberos with cloudera Manager

**Comment by kumarcraja** [comment]
uploaded files up to kerberos integration with cloudera manager

**Comment by kumarcraja** [comment]
After enabling kerberos.

Unable to run 
hdfs dfs -ls /user/kumarcraja

as kumarcraja user.

Added principal kumarcraja using kadmin.local.

After kinit now able to view files and able to run yarn jobs.

**Comment by mfernest** [comment]
👍
