### ISSUE TITLE
clients lab

### ISSUE THREAD

**Issue by kumarcraja** [kumarcraja/cloudera#6]
clients lab started

**Comment by kumarcraja** [comment]
Exporting linux users to hue interface using scripts.

While doing we have issue ... To resolve the same used the following environment variables

export HUE_SECRET_KEY=cloudera
export HUE_IGNORE_PASSWORD_SCRIPT_ERRORS=1
export HUE_DATABASE_PASSWORD=Netweb@123

**Comment by kumarcraja** [comment]
completed and uploaded png files

**Comment by mfernest** [comment]
`0_unix_login.png` - can't tell who is logged in.

INC
